FROM ruby:3.3.6-slim

# Set working directory
WORKDIR /app

# Install essential packages
RUN apt-get update -qq && \
  apt-get install -y --no-install-recommends \
  build-essential \
  libpq-dev \
  curl \
  git \
  postgresql-client && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

# Copy dependency files
COPY Gemfile Gemfile.lock ./

# Install Ruby dependencies
RUN bundle install

# Copy the application code
COPY . .

# Set Rails environment
ENV RAILS_ENV=development

COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["/usr/bin/entrypoint.sh"]

# Expose port
EXPOSE 3000

# Start the server
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
